import {StyleSheet} from 'react-native';

export const detailStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    height: 300,
    width: '100%',
    borderRadius: 15,
    position: 'absolute',
    top: 0,
  },
  text: {
    marginTop: 310,
    padding: 16,
    fontSize: 25,
    fontWeight: '700',
  },
  listContainer: {
    flex: 1,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  stepsTitle: {
    marginLeft: 16,
    fontSize: 20,
    fontWeight: '700',
  },
  stepItem: {
    flex: 1,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  stepItemText: {
    fontSize: 20,
    color: '#fff',
  },
  stepItemContainer: {
    position: 'relative',
    margin: 3,
    width: '47%',
  },
  statusContainer: {
    paddingVertical: 10,
    flexDirection: 'row',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  statusTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FF0000',
    marginRight: 10,
  },
  statusText: {
    fontSize: 16,
    fontWeight: '500',
  },
  buttonContainer: {
    flex: 0.05,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonText: {
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    height: 20,
    width: 20,
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  closeButtonText: {
    color: '#fff',
  },
  modalView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '500',
    marginBottom: 15,
    color: '#fff',
  },
  modalInput: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 15,
    width: '80%',
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 40,
    gap: 10,
  },
  modalAddButton: {
    flex: 1,
    backgroundColor: '#007BFF',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: '#FF0000',
    padding: 10,
    borderRadius: 5,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ButtonTitle: {
    color: '#fff',
    fontSize: 16,
  },
});
